version: "3.8"

services:
  backend:
    build:
      context: ./Engine
      dockerfile: Dockerfile
    container_name: squares-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: squares-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
